language: csharp
solution: JsonLib/JsonLib.sln
script:
  - xbuild /p:Configuration=Release JsonLib/JsonLib.sln
matrix:
  include:
    - dotnet: 1.0.0-preview2-003121
      mono: none
      env: DOTNETCORE=1
    - mono: latest
